# config.yaml
model_name: "cointegrated/rubert-tiny-sentiment-balanced"
batch_size: 512

# Списки слов для фильтрации и обработки текста.
narichiya_stepeni: [
    "очень", "сильно", "чрезвычайно", "весьма", "крайне", "исключительно", "необычайно", "колоссально", 
    "неимоверно", "ужасно", "безмерно", "невероятно", "совершенно", "абсолютно", "капитально", "дико", 
    "неописуемо", "бесконечно", "потрясающе", "несказанно", "сказочно", "фантастически", "гигантски", 
    "необыкновенно", "супер", "чрезмерно", "изумительно", "отлично", "восхитительно", "превосходно", 
    "грандиозно", "максимально", "поразительно", "бесподобно", "безгранично", "огромно", "гиперболически", 
    "значительно", "существенно", "немыслимо", "экстремально"
]

sravnitelno_usilitelnye_konstruktsii: [
    "настолько", "так", "столь", "чуть-чуть", "немного", "вполне", "очень", "более", "менее", "гораздо", 
    "намного", "чуть", "слишком", "сверх", "сильно", "крайне", "безмерно", "необычайно", "невероятно", 
    "чересчур", "едва", "еле", "весьма", "особенно", "предельно", "максимально", "почти"
]

# Слова, выражающие довольство и недовольство для анализа настроения текста.
slova_dovolstva: ["отличный", "хороший", "шикарный", "офигенный", "превосходный", "замечательный", "потрясающий", "великолепный", "прекрасный", "изумительный", "фантастический", "удивительный", "роскошный", "невероятный", "зачётный", "суперский", "классный", "идеальный", "восторг", "чудесный", "блистательный", "безупречный", "радостный", "позитивный", "приятный", "сказочный", "крутой", "гениальный", "бесподобный"]

slova_neudovolstva: ["плохой", "ужасный", "отвратительный", "ужасный", "омерзительный", "неприятный", "неудовлетворительный", "скверный", "жуткий", "страшный", "мерзкий", "отталкивающий", "паршивый", "никакой", "негодный", "беспросветный", "недостойный", "отстойный", "гнусный", "гадкий", "худший", "гнусный", "убогий", "ничтожный", "отвратный", "жалкий"]
