# config.yaml
model_name: "cointegrated/rubert-tiny-sentiment-balanced"
batch_size: 512

# Списки слов для фильтрации и обработки текста.
narichiya_stepeni: [
    "очень", "сильно", "чрезвычайно", "весьма", "крайне", "исключительно", "необычайно", "колоссально", 
    "неимоверно", "ужасно", "безмерно", "невероятно", "совершенно", "абсолютно", "капитально", "дико", 
    "неописуемо", "бесконечно", "потрясающе", "несказанно", "сказочно", "фантастически", "гигантски", 
    "необыкновенно", "супер", "чрезмерно", "изумительно", "отлично", "восхитительно", "превосходно", 
    "грандиозно", "максимально", "поразительно", "бесподобно", "безгранично", "огромно", "гиперболически", 
    "значительно", "существенно", "немыслимо", "экстремально"
]

sravnitelno_usilitelnye_konstruktsii: [
    "настолько", "так", "столь", "чуть-чуть", "немного", "вполне", "очень", "более", "менее", "гораздо", 
    "намного", "чуть", "слишком", "сверх", "сильно", "крайне", "безмерно", "необычайно", "невероятно", 
    "чересчур", "едва", "еле", "весьма", "особенно", "предельно", "максимально", "почти"
]

# Слова, выражающие довольство и недовольство для анализа настроения текста.
slova_dovolstva: ["отличный", "хороший", "шикарный", "офигенный", "превосходный", "замечательный", "потрясающий", "великолепный", "прекрасный", "изумительный", "фантастический", "удивительный", "роскошный", "невероятный", "зачётный", "суперский", "классный", "идеальный", "восторг", "чудесный", "блистательный", "безупречный", "радостный", "позитивный", "приятный", "сказочный", "крутой", "гениальный", "бесподобный"]

slova_neudovolstva: ["плохой", "ужасный", "отвратительный", "ужасный", "омерзительный", "неприятный", "неудовлетворительный", "скверный", "жуткий", "страшный", "мерзкий", "отталкивающий", "паршивый", "никакой", "негодный", "беспросветный", "недостойный", "отстойный", "гнусный", "гадкий", "худший", "гнусный", "убогий", "ничтожный", "отвратный", "жалкий"]

aspect_groups_main: {
    'Товар': ['товар', 'продукт', 'вещь'],
    'Бренд': ['бренд', 'марка', 'лейбл', 'фирменное наименование', 'брендовый знак'],
    'Модель': ['модель', 'серия', 'вариант исполнения', 'модельный ряд', 'конфигурация'],
    'Артикул': ['артикул', 'код товара', 'идентификатор', 'штрихкод', 'номер изделия'],
    'Название': ['название', 'наименование', 'титул', 'обозначение'],
    'Цена': ['цена', 'стоимость', 'ценник', 'тариф', 'рыночная стоимость', 'цена продажи'],
    'Скидка': ['скидка', 'дисконт', 'акция', 'ценовое снижение', 'скидочный процент', 'снижение цены'],
    'Размер': ['размер', 'габариты', 'величина', 'размерность', 'размерные показатели'],
    'Цвет': ['цвет', 'оттенок', 'расцветка', 'цветовой тон', 'палитра'],
    'Вес': ['вес', 'масса', 'тяжесть', 'грузоподъемность', 'массовый показатель'],
    'Материал': ['материал', 'сырье', 'основа', 'составляющая', 'вещество'],
    'Объем': ['объем', 'вместимость', 'размер', 'кубометры', 'литраж'],
    'Мощность': ['мощность', 'энергопотребление', 'ватты', 'киловатты', 'мощностной показатель'],
    'Количество': ['количество', 'число', 'объем', 'штуки', 'численность'],
    'Количество в упаковке': ['количество в упаковке', 'число единиц', 'упаковочная единица', 'упаковка товара'],
    'Длина': ['длина', 'протяженность', 'метраж', 'длина изделия', 'длина в упаковке'],
    'Ширина': ['ширина', 'размах', 'ширина изделия', 'ширина в упаковке', 'ширина габарита'],
    'Высота': ['высота', 'размер по вертикали', 'высотный показатель', 'вертикальная протяженность'],
    'Глубина': ['глубина', 'толщина', 'глубинный размер', 'глубинный показатель'],
    'Диаметр': ['диаметр', 'радиус', 'ширина круга', 'диаметр изделия'],
    'Толщина': ['толщина', 'толщина стенки', 'размер толщины', 'толщинный показатель'],
    'Тип': ['тип', 'категория', 'разновидность', 'вид'],
    'Тип устройства': ['тип устройства', 'категория устройства', 'вид техники'],
    'Назначение': ['назначение', 'предназначение', 'функция', 'использование'],
    'Гарантия': ['гарантия', 'гарантийный срок', 'срок гарантии', 'гарантийное обязательство'],
    'Совместимость': ['совместимость', 'совместимость с устройствами', 'поддержка'],
    'Упаковка': ['упаковка', 'тара', 'футляр', 'обертка', 'упаковочный материал'],
    'Производитель': ['производитель', 'изготовитель', 'компания-производитель'],
    'Страна производитель': ['страна производитель', 'страна происхождения', 'страна изготовления'],
    'Состав': ['состав', 'ингредиенты', 'компоненты', 'составляющие'],
    'Особенности': ['особенности', 'характеристики', 'специфические свойства'],
    'Форма': ['форма', 'контур', 'формообразование'],
    'Применение': ['применение', 'использование', 'эксплуатация'],
    'Максимальная нагрузка': ['максимальная нагрузка', 'нагрузочный предел', 'допустимая нагрузка'],
    'Ёмкость': ['ёмкость', 'вместимость', 'объемная емкость'],
    'Рекомендации по уходу': ['рекомендации по уходу', 'уход', 'уходовые рекомендации'],
    'Инструкция по применению': ['инструкция по применению', 'инструкция', 'руководство пользователя'],
    'Срок годности': ['срок годности', 'период хранения', 'дата годности'],
    'Сертификат': ['сертификат', 'документ о качестве', 'сертификационный документ']
}

aspect_groups_devices: {
    'Мощность': ['мощность', 'энергетическая мощность', 'энергопотребление', 'ватты', 'киловатты'],
    'Напряжение': ['напряжение', 'вольтаж', 'электрическое напряжение'],
    'Частота': ['частота', 'гц', 'частотный диапазон'],
    'Аккумулятор': ['аккумулятор', 'батарея', 'источник питания'],
    'Ёмкость батареи': ['ёмкость батареи', 'вместимость аккумулятора', 'заряд батареи'],
    'Время работы': ['время работы', 'время автономной работы', 'время эксплуатации'],
    'Время зарядки': ['время зарядки', 'время восполнения заряда', 'время подзарядки'],
    'Интерфейсы': ['интерфейсы', 'подключения', 'разъемы'],
    'Совместимость': ['совместимость', 'поддерживаемые устройства', 'подключаемые устройства'],
    'Управление': ['управление', 'контроль', 'регулировка'],
    'Тип подключения': ['тип подключения', 'способ подключения', 'тип соединения'],
    'Защита от перегрузки': ['защита от перегрузки', 'перегрузочная защита', 'перегрузка защиты'],
    'Светодиодный индикатор': ['светодиодный индикатор', 'LED индикатор', 'световой индикатор'],
    'Поддержка форматов': ['поддержка форматов', 'поддерживаемые форматы', 'совместимые форматы'],
    'Разрешение экрана': ['разрешение экрана', 'пиксельное разрешение', 'экранное разрешение'],
    'Сенсорный экран': ['сенсорный экран', 'тачскрин', 'экран с сенсорным управлением'],
    'Встроенные функции': ['встроенные функции', 'функционал', 'дополнительные функции'],
    'Подсветка': ['подсветка', 'световое оформление', 'световой эффект'],
    'Звук': ['звук', 'аудио', 'звуковое сопровождение'],
    'Вибрация': ['вибрация', 'виброотклик', 'вибрационный эффект'],
    'Динамик': ['динамик', 'колонка', 'звуковой динамик'],
    'Микрофон': ['микрофон', 'звукоулавливающий прибор', 'аудиовход'],
    'Камера': ['камера', 'видеоустройство', 'фотоаппарат']
}

aspect_groups_cars: {
    'Тип автомобиля': ['тип автомобиля', 'автомобильный класс', 'категория авто'],
    'Модель автомобиля': ['модель автомобиля', 'модель авто', 'автомобильная модель'],
    'Тип кузова': ['тип кузова', 'кузов', 'тип автомобильного кузова'],
    'Сезонность': ['сезонность', 'сезон', 'временной период'],
    'Индекс нагрузки': ['индекс нагрузки', 'нагрузочный индекс', 'допустимая нагрузка'],
    'Индекс скорости': ['индекс скорости', 'скоростной индекс', 'максимальная скорость'],
    'Шиповка': ['шиповка', 'наличие шипов', 'шипованность'],
    'Тип топлива': ['тип топлива', 'вид топлива', 'топливная категория'],
    'Объем двигателя': ['объем двигателя', 'объем моторного отсека', 'моторная ёмкость'],
    'Тип привода': ['тип привода', 'привод', 'приводной механизм'],
    'Тип трансмиссии': ['тип трансмиссии', 'коробка передач', 'трансмиссионный тип'],
    'Состав смеси': ['состав смеси', 'смесь', 'ингредиенты смеси'],
    'Присадки': ['присадки', 'добавки', 'смазочные добавки'],
    'Вязкость': ['вязкость', 'масляная вязкость', 'плотность масла'],
    'Тип масла': ['тип масла', 'масляная категория', 'вид масла'],
    'Количество дверей': ['количество дверей', 'двери', 'дверной механизм'],
    'Количество сидений': ['количество сидений', 'сиденья', 'число мест'],
    'Тип фильтра': ['тип фильтра', 'фильтрационный механизм', 'категория фильтра'],
    'Режим работы': ['режим работы', 'рабочий режим', 'рабочий режим устройства'],
    'Номинальное напряжение': ['номинальное напряжение', 'рабочее напряжение', 'электрическое напряжение'],
    'Рабочая температура': ['рабочая температура', 'температурный диапазон', 'температура эксплуатации'],
    'Степень защиты': ['степень защиты', 'защитный класс', 'класс защиты'],
    'Уровень шума': ['уровень шума', 'шум', 'звуковой уровень'],
    'Емкость аккумулятора': ['емкость аккумулятора', 'вместимость батареи', 'аккумуляторная ёмкость']
}

aspect_groups_clothes: {
    'Размер': ['размер', 'размерная сетка', 'размерность'],
    'Цвет': ['цвет', 'цветовой тон', 'расцветка'],
    'Материал': ['материал', 'ткань', 'материал изготовления'],
    'Фасон': ['фасон', 'стиль', 'крой'],
    'Стиль': ['стиль', 'дизайн', 'мода'],
    'Тип одежды': ['тип одежды', 'категория одежды', 'вид одежды'],
    'Тип обуви': ['тип обуви', 'категория обуви', 'вид обуви'],
    'Подкладка': ['подкладка', 'внутренняя отделка', 'внутренний материал'],
    'Утеплитель': ['утеплитель', 'утепляющий слой', 'изоляция'],
    'Сезон': ['сезон', 'временной период', 'сезонность'],
    'Пол': ['пол', 'гендер', 'половая принадлежность'],
    'Возраст': ['возраст', 'возрастная категория', 'возрастная группа'],
    'Тип застежки': ['тип застежки', 'застежка', 'механизм застегивания'],
    'Высота каблука': ['высота каблука', 'размер каблука', 'каблучный показатель'],
    'Декор': ['декор', 'украшение', 'декоративные элементы'],
    'Тип подошвы': ['тип подошвы', 'подошва', 'вид подошвы'],
    'Защита от воды': ['защита от воды', 'водозащитный слой', 'водонепроницаемость'],
    'Степень теплоизоляции': ['степень теплоизоляции', 'утепление', 'изоляционные характеристики'],
    'Форма носка': ['форма носка', 'носковая часть', 'форма передней части'],
    'Форма каблука': ['форма каблука', 'каблучная форма', 'каблучный дизайн']
}

aspect_groups_appliances: {
    'Тип устройства': ['тип устройства', 'категория техники', 'вид устройства'],
    'Мощность': ['мощность', 'энергопотребление', 'мощностной показатель'],
    'Энергопотребление': ['энергопотребление', 'энергетическая эффективность', 'потребляемая мощность'],
    'Ёмкость': ['ёмкость', 'вместимость', 'объем бака'],
    'Управление': ['управление', 'контроль', 'регулировка'],
    'Функции': ['функции', 'дополнительные функции', 'встроенные функции'],
    'Программы': ['программы', 'режимы работы', 'настройки'],
    'Защита от перегрева': ['защита от перегрева', 'перегрев', 'термозащита'],
    'Защита от протечек': ['защита от протечек', 'протечка', 'водозащитный механизм'],
    'Класс энергопотребления': ['класс энергопотребления', 'энергетический класс', 'класс энергоэффективности'],
    'Уровень шума': ['уровень шума', 'шум', 'звуковой уровень'],
    'Тип установки': ['тип установки', 'способ установки', 'вид монтажа'],
    'Тип крепления': ['тип крепления', 'механизм крепления', 'способ фиксации'],
    'Длина шнура': ['длина шнура', 'шнур', 'длина кабеля'],
    'Объем воды': ['объем воды', 'водяная ёмкость', 'вместимость воды'],
    'Давление воды': ['давление воды', 'водяное давление', 'напор воды'],
    'Температура нагрева': ['температура нагрева', 'температура воды', 'температурный режим'],
    'Объем бака': ['объем бака', 'вместимость бака', 'емкость бака']
}

aspect_groups_beauty: {
    'Тип кожи': ['тип кожи', 'категория кожи', 'тип эпидермиса'],
    'Тип волос': ['тип волос', 'категория волос', 'вид волос'],
    'Объём': ['объём', 'вместимость', 'размер'],
    'Состав': ['состав', 'ингредиенты', 'компоненты'],
    'Назначение': ['назначение', 'предназначение', 'функция'],
    'Рекомендации по применению': ['рекомендации по применению', 'инструкция', 'способ использования'],
    'Возрастная группа': ['возрастная группа', 'возрастная категория', 'возраст'],
    'Пол': ['пол', 'гендер', 'половая принадлежность'],
    'Тип средства': ['тип средства', 'категория', 'вид средства'],
    'Форма выпуска': ['форма выпуска', 'тип упаковки', 'вид упаковки'],
    'Время воздействия': ['время воздействия', 'продолжительность действия', 'время применения'],
    'Уровень защиты SPF': ['уровень защиты SPF', 'защита от солнца', 'солнцезащитный фактор'],
    'Аромат': ['аромат', 'запах', 'парфюм'],
    'Текстура': ['текстура', 'структура', 'консистенция'],
    'Влагостойкость': ['влагостойкость', 'водоотталкивание', 'водостойкость'],
    'Гипоаллергенность': ['гипоаллергенность', 'неаллергенность', 'антиаллергенный эффект']
}

aspect_groups_toys: {
    'Возраст': ['возраст', 'возрастная категория', 'возрастной диапазон'],
    'Пол': ['пол', 'гендер', 'половая принадлежность'],
    'Материал': ['материал', 'основа', 'сырье'],
    'Цвет': ['цвет', 'оттенок', 'расцветка'],
    'Тип игрушки': ['тип игрушки', 'вид игрушки', 'категория игрушек'],
    'Назначение': ['назначение', 'предназначение', 'функция'],
    'Комплектация': ['комплектация', 'состав набора', 'включенные элементы'],
    'Количество деталей': ['количество деталей', 'число элементов', 'детали'],
    'Размер упаковки': ['размер упаковки', 'габариты', 'величина упаковки'],
    'Безопасность': ['безопасность', 'защитные меры', 'безопасные материалы'],
    'Тип батареек': ['тип батареек', 'категория батареек', 'батарейки'],
    'Развиваемые навыки': ['развиваемые навыки', 'образовательные элементы', 'обучение']
}

aspect_groups_books: {
    'Формат': ['формат', 'размер', 'размеры страниц'],
    'Количество страниц': ['количество страниц', 'число страниц', 'страничный объем'],
    'Тип обложки': ['тип обложки', 'вид обложки', 'переплет'],
    'Тип бумаги': ['тип бумаги', 'бумажный материал', 'вид бумаги'],
    'Цвет бумаги': ['цвет бумаги', 'бумажный цвет', 'оттенок бумаги'],
    'Листовка': ['листовка', 'брошюра', 'информационный лист'],
    'Тип переплета': ['тип переплета', 'переплет', 'переплетный материал'],
    'Размер': ['размер', 'формат', 'размеры изделия'],
    'Тематика': ['тематика', 'предмет', 'содержание'],
    'Язык': ['язык', 'языковой формат', 'перевод'],
    'Иллюстрации': ['иллюстрации', 'рисунки', 'картинки'],
    'Назначение': ['назначение', 'предназначение', 'функция']
}

aspect_groups_furniture: {
    'Тип мебели': ['тип мебели', 'категория мебели', 'вид мебели'],
    'Материал': ['материал', 'основа', 'материалы изготовления'],
    'Цвет': ['цвет', 'оттенок', 'расцветка'],
    'Размеры': ['размеры', 'габариты', 'размерные параметры'],
    'Стиль': ['стиль', 'дизайн', 'оформление'],
    'Количество ящиков': ['количество ящиков', 'число секций', 'секцийность'],
    'Тип фурнитуры': ['тип фурнитуры', 'фурнитура', 'категория фурнитуры'],
    'Высота сиденья': ['высота сиденья', 'размер по вертикали', 'вертикальная высота'],
    'Ширина сиденья': ['ширина сиденья', 'размер по горизонтали', 'ширинный показатель'],
    'Длина сиденья': ['длина сиденья', 'размер по горизонтали', 'длина'],
    'Максимальная нагрузка': ['максимальная нагрузка', 'допустимая нагрузка', 'предельная нагрузка'],
    'Тип крепления': ['тип крепления', 'крепеж', 'механизм фиксации'],
    'Комплектация': ['комплектация', 'состав набора', 'включенные элементы'],
    'Тип покрытия': ['тип покрытия', 'вид покрытия', 'покрывающий слой'],
    'Тип механизма': ['тип механизма', 'механизм', 'категория механизма'],
    'Регулировка высоты': ['регулировка высоты', 'настройка по высоте', 'высотная регулировка'],
    'Подсветка': ['подсветка', 'световое оформление', 'световой эффект']
}

aspect_groups_garden: {
    'Тип растения': ['тип растения', 'вид растения', 'категория растений'],
    'Тип грунта': ['тип грунта', 'категория почвы', 'грунт'],
    'Тип удобрения': ['тип удобрения', 'категория удобрений', 'удобрение'],
    'Сезонность': ['сезонность', 'сезон', 'временной период'],
    'Тип семян': ['тип семян', 'категория семян', 'семена'],
    'Тип почвы': ['тип почвы', 'почва', 'вид почвы'],
    'Тип полива': ['тип полива', 'полив', 'вид полива'],
    'Размер участка': ['размер участка', 'площадь участка', 'размер земли'],
    'Состав удобрения': ['состав удобрения', 'ингредиенты удобрения', 'компоненты удобрения'],
    'Способ посадки': ['способ посадки', 'метод посадки', 'посадочный способ'],
    'Тип орудия': ['тип орудия', 'категория инструментов', 'инструмент'],
    'Длина шланга': ['длина шланга', 'шланг', 'длина водопроводного шланга'],
    'Мощность насоса': ['мощность насоса', 'насосная мощность', 'мощность оборудования']
}